# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6c35b12ccb001724c8dd3658a1f2dbf3706ce5eb9366e4748d3f2d0531b3e38df580a6f3ec548bb4f4937c3e8ff5b5b0927598617abac65ea66e7a7540b01a4c

test:
  secret_key_base: 94568f52dc78d2fc46df199b5306ea2a02026a86447ea81796210b31ee0f8b3a58e297c39b60bcea4e8f4fa3e4584fa28cdef0f6c4e06bd597dbbd16364e12af

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
